### ISSUE TITLE
Don't error on first run

### ISSUE THREAD

**Issue by timsuchanek** [mcataford/packwatch#16]
It's quite weird, that although the first run was successful, it exits with exit code 1.
As a user new to `packwatch`, I'm wondering what I did wrong.

![image](https://user-images.githubusercontent.com/1094804/78921823-cc07cb00-7a95-11ea-9786-88db86eaf174.png)

**Comment by mcataford** [comment]
Hi @timsuchanek! This behaviour is meant to prevent accidental passes in CI if you omit your manifest but have `packwatch` as a CI step! In hindsight, this should've been documented since it's entirely expected. I'll be publishing some docs this weekend and will amend the cli messaging to make this clear. :rocket:

**Comment by mcataford** [comment]
Appropriate CLI messaging and docs were added to document this behaviour, although I might tweak this behaviour in the near future in favour of leveraging the oft-used `CI` flag to fail on no-manifest instead. Stay tuned!

In the meantime, closing this issue and opening another re: the `CI` flag.
